Repository AritDeveloperCircle/findyourpeople, pull requests merged in 2023-06, with the labels that each got.

#127 Seyi - Styling of Manager Hero using tailwind
  public/Manager dashboard flat character.png
  src/components/Manager/CommunityManagerDetails.js
Labels: PLANNING 🧐

#108 Neka single listing fix module name
  public/LOGO.png
  src/components/Header/NavBar.js
  src/components/Header/NavBar.module.css
  src/pages/managerDashboard.js
  src/pages/singleListing.js
  src/styles/singleListing.module.css
Labels: BUG 🐛

#94 Neka style navbar on landing page
  src/components/Header/NavBar.js
  src/components/common/ReusableNavLink.js
Labels: STYLING ONLY

#128 Neka-Manager Form
  public/arrow-right-line.png
  src/pages/managerDashboard.js
  src/pages/managerForm.js
  src/styles/managerForm.module.css
Labels: PLANNING 🧐

#114 Footer css
  src/components/common/FooterBar.js
  src/styles/globals.css
  tailwind.config.js
Labels: STYLING ONLY

#133 Seyi - styled communityDashboard Link
  src/pages/[community_id].js
Labels: STYLING ONLY

#150 Chibuzo-listing-css
  public/avatar 2.png
  public/avatar 3.png
  public/avatar 4.png
  public/avatar 5.png
  public/avatar 6.png
  src/components/landing/listing.js
Labels: STYLING ONLY
